name 'anothertestrepo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures anothertestrepo'
long_description 'Installs/Configures anothertestrepo'
version '0.1.0'
